### Listar todos los departamentos
GET http://localhost:3000/api/department


###

### Buscar departamento por nombre
GET http://localhost:3000/api/department/Sistemas


###

### Crear departamento
POST http://localhost:3000/api/department
Content-Type: application/json

{
    "name": "Sistemas"
}


###

### Eliminar departamento por ID
DELETE http://localhost:3000/api/department/2


###

### Actualizar departamento
PATCH http://localhost:3000/api/department/1
Content-Type: application/json

{
    "name": "Tecnologia"
}