### Create Support Device
POST http://localhost:3000/api/supportDevice
Content-Type: application/json

{
    "id_device" : "1",
    "name" : "Lenovo",
    "description" : "computador dañado",
    "type" : "computador",
    "status" : "Sin arreglo"
}

###

### List Support Device

GET http://localhost:3000/api/supportDevice

###

### Update Support device

PATCH http://localhost:3000/api/supportDevice/1
Content-Type: application/json

{
    "name" : "Apple"
}

###

### Delete Support Device

DELETE http://localhost:3000/api/supportDevice/1

###